name: Build and Deploy
on:
  [push, workflow_dispatch]
env:
  # VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  # VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
  VITE_SUPABASE_URL: https://ogmrlrvbnpczlkhntzgp.supabase.co
  VITE_SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbXJscnZibnBjemxraG50emdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjEwMzY5NDYsImV4cCI6MjAzNjYxMjk0Nn0.1ZtXpr1PO4C5LPqHYjOCMpgkfAiBcx1dgomRlQXnUO8

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: tree
    - uses: actions/checkout@v4
    - run: tree
    - run: cd learning-management-app
    - run: npm install
      working-directory: learning-management-app

    - name: build
      run: |
        npm run build
      working-directory: learning-management-app

    - run: npm install -g firebase-tools
      working-directory: learning-management-app
    - run: firebase deploy --token 1//0e_3b83r3hNyeCgYIARAAGA4SNwF-L9IrBiD9pa77TP9meyWfC6uky5KyEud12m5s6hlyLu_AgH-Q4WKP4_l_pqJYwiJeAC3ShcY
      working-directory: learning-management-app
