name: Build and Deploy
on:
  [push, workflow_dispatch]
env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
  MESSAGE: "test_message"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: test-environment
    steps:
    - run: echo $ {{ secrets.VITE_SUPABASE_URL }}
    - run: echo $ {{ secrets.VITE_SUPABASE_KEY }}
    # - run: tree
    # - uses: actions/checkout@v4
    # - run: tree
    # - run: cd learning-management-app
    # - run: npm install
    #   working-directory: learning-management-app

    # - name: build
    #   run: |
    #     touch .env
    #     npm run build
    #     echo "this is env"
    #     echo "$VITE_SUPABASE_URL"
    #     echo "$VITE_SUPABASE_KEY"
    #     echo "$MESSAGE"
    #   working-directory: learning-management-app

    # - run: npm install -g firebase-tools
    #   working-directory: learning-management-app
    # - run: firebase deploy --token 1//0e_3b83r3hNyeCgYIARAAGA4SNwF-L9IrBiD9pa77TP9meyWfC6uky5KyEud12m5s6hlyLu_AgH-Q4WKP4_l_pqJYwiJeAC3ShcY
    #   working-directory: learning-management-app
