name: degital-meishi-job-for-delete-previous-user
on:
  workflow_dispatch:
jobs:
  # Job1用のコンテナ環境が用意される
  delete-previous-user:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: npm ci
        working-directory: degital-meishi-app
      - name: execute
        run: node --no-warnings --loader ts-node/esm ./src/batch/index.ts
        working-directory: degital-meishi-app