name: deploy-next-tech-blog
on:
  push:
    paths:
      - "next-tech-blog/*"
    workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo 'called'