name: deploy-next-tech-blog
on:
  push:
    paths:
      - "next-tech-blog/*"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v4
        run: npm run test
        working-directory: next-tech-blog