name: deploy-next-tech-blog
on:
  push:
    paths:
      - "next-tech-blog/*"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v4

      - name: npm install
        run: npm install
        working-directory: npm install

      - name: test
        run: npm run test
        working-directory: next-tech-blog