name: deploy-next-tech-blog
on:
  push:
    paths:
      - "next-tech-blog/**"
      - ".github/workflows/*"
    workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v2

      - name: npm install
        run: npm install
        working-directory: next-tech-blog

      - name: run tests
        run: npm run test
        working-directory: next-tech-blog

      - name: build
        run: npm run build
        working-directory: next-tech-blog

      - name: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PRJ_ID }}
