name: deploy-next-tech-blog
on:
  push:
    paths:
      - "next-tech-blog/**"
    workflow_dispatch:
jobs:
  build-and-deploy:
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm install

      - name: run tests
        run: npm run test

      - name: build
        run:
          npm run build

      - name: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          # vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}