name: Sample
on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: tree
    - uses: actions/checkout@v4
    - run: tree
    - run: cd learning-management-app
    - run: npm install
    - run: npm run build
    - run: firebase deploy
