name: Build and Deploy
on:
  [push, workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: tree
    - uses: actions/checkout@v4
    - run: tree
    - run: cd learning-management-app
    - run: npm install
      working-directory: learning-management-app

    - name: build
      run: |
        touch .env
        echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> .env
        echo "VITE_SUPABASE_KEY=$VITE_SUPABASE_KEY" >> .env
        cat .env
        npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      working-directory: learning-management-app

    - run: npm install -g firebase-tools
      working-directory: learning-management-app
    - run: firebase deploy --token 1//0e_3b83r3hNyeCgYIARAAGA4SNwF-L9IrBiD9pa77TP9meyWfC6uky5KyEud12m5s6hlyLu_AgH-Q4WKP4_l_pqJYwiJeAC3ShcY
      working-directory: learning-management-app
