name: Hello World
on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: tree
    - users: actions/checkout@v4
    - run: tree
    - run: cd learning-management-app
    # - run: npm run build
    # - run: firebase deploy
