name: v2-learning-management-app-firebase-hosting
on:
  push:
    paths:
      - "v2_learning-management-app/*"
  workflow_dispatch
# env:
#   VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
#   VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: test-environment
    steps:
    - uses: actions/checkout@v4
    - run: cd v2_learning-management-app
    - run: npm install
      working-directory: v2_learning-management-app

    - name: build
      run: |
        touch .env
        npm run build
        # echo "this is env"
        # echo "$VITE_SUPABASE_URL"
        # echo "$VITE_SUPABASE_KEY"
      working-directory: v2_learning-management-app

    # - name: run test
    #   run: |
    #     npm run test
    #   working-directory: learning-management-app
      
    - run: npm install -g firebase-tools
      working-directory: v2_learning-management-app
    - run: firebase deploy --token 1//0eE_glusABF_qCgYIARAAGA4SNwF-L9IrkIImnWNZpfdEs0jj8zRRM1KkarkcFgarTtq0GpktzA1ryNzeAFz5bl8BghcUz7WKxXA
      working-directory: v2_learning-management-app
